//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristPlanner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouristPlanner.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes tener dos carreteras en el mismo lugar dirigidas hacia la misma ciudad..
        /// </summary>
        internal static string box_aristaDuplicada {
            get {
                return ResourceManager.GetString("box_aristaDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se añadio exitosamente .
        /// </summary>
        internal static string box_ciudadAgregada {
            get {
                return ResourceManager.GetString("box_ciudadAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se edito exitosamente.
        /// </summary>
        internal static string box_ciudadEditada {
            get {
                return ResourceManager.GetString("box_ciudadEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se elimino exitosamente.
        /// </summary>
        internal static string box_ciudadEliminada {
            get {
                return ResourceManager.GetString("box_ciudadEliminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes borrar una ciudad con rutas. Elmina la ruta primero..
        /// </summary>
        internal static string box_errorCiudadBorrar {
            get {
                return ResourceManager.GetString("box_errorCiudadBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se permiten duplicados.
        /// </summary>
        internal static string box_noDuplicates {
            get {
                return ResourceManager.GetString("box_noDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ciudad .
        /// </summary>
        internal static string box_noExiste1 {
            get {
                return ResourceManager.GetString("box_noExiste1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no existe.
        /// </summary>
        internal static string box_noExiste2 {
            get {
                return ResourceManager.GetString("box_noExiste2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta ha sido añadida.
        /// </summary>
        internal static string box_rutaAgregada {
            get {
                return ResourceManager.GetString("box_rutaAgregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta ha sido editada.
        /// </summary>
        internal static string box_rutaEditada {
            get {
                return ResourceManager.GetString("box_rutaEditada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta ha sido eliminada.
        /// </summary>
        internal static string box_rutaElminada {
            get {
                return ResourceManager.GetString("box_rutaElminada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ruta .
        /// </summary>
        internal static string box_rutaNoExiste1 {
            get {
                return ResourceManager.GetString("box_rutaNoExiste1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no existe.
        /// </summary>
        internal static string box_rutaNoExiste2 {
            get {
                return ResourceManager.GetString("box_rutaNoExiste2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta alterna.
        /// </summary>
        internal static string busqueda__rutaAlterna {
            get {
                return ResourceManager.GetString("busqueda__rutaAlterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambos.
        /// </summary>
        internal static string busqueda_ambos {
            get {
                return ResourceManager.GetString("busqueda_ambos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambos.
        /// </summary>
        internal static string busqueda_ambosSeleccionado {
            get {
                return ResourceManager.GetString("busqueda_ambosSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        internal static string busqueda_costo {
            get {
                return ResourceManager.GetString("busqueda_costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterio de búsqueda.
        /// </summary>
        internal static string busqueda_criterio {
            get {
                return ResourceManager.GetString("busqueda_criterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia.
        /// </summary>
        internal static string busqueda_distancia {
            get {
                return ResourceManager.GetString("busqueda_distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad de Inicio.
        /// </summary>
        internal static string busqueda_inicio {
            get {
                return ResourceManager.GetString("busqueda_inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        internal static string busqueda_lbl_costo {
            get {
                return ResourceManager.GetString("busqueda_lbl_costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia.
        /// </summary>
        internal static string busqueda_lbl_distancia {
            get {
                return ResourceManager.GetString("busqueda_lbl_distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicia.
        /// </summary>
        internal static string busqueda_lbl_inicia {
            get {
                return ResourceManager.GetString("busqueda_lbl_inicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termina.
        /// </summary>
        internal static string busqueda_lbl_termina {
            get {
                return ResourceManager.GetString("busqueda_lbl_termina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        internal static string busqueda_lbl_tiempo {
            get {
                return ResourceManager.GetString("busqueda_lbl_tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio de transporte.
        /// </summary>
        internal static string busqueda_lbl_transporte {
            get {
                return ResourceManager.GetString("busqueda_lbl_transporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio de Transporte.
        /// </summary>
        internal static string busqueda_medioTransporte {
            get {
                return ResourceManager.GetString("busqueda_medioTransporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionaste el mismo nodo. Selecciona otro..
        /// </summary>
        internal static string busqueda_mismo {
            get {
                return ResourceManager.GetString("busqueda_mismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto rentado.
        /// </summary>
        internal static string busqueda_privado {
            get {
                return ResourceManager.GetString("busqueda_privado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Rentado.
        /// </summary>
        internal static string busqueda_privadoSeleccionado {
            get {
                return ResourceManager.GetString("busqueda_privadoSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporte público.
        /// </summary>
        internal static string busqueda_publico {
            get {
                return ResourceManager.GetString("busqueda_publico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camion.
        /// </summary>
        internal static string busqueda_publicoSeleccionado {
            get {
                return ResourceManager.GetString("busqueda_publicoSeleccionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta más corta.
        /// </summary>
        internal static string busqueda_rutaCorta {
            get {
                return ResourceManager.GetString("busqueda_rutaCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad donde termina.
        /// </summary>
        internal static string busqueda_termina {
            get {
                return ResourceManager.GetString("busqueda_termina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo.
        /// </summary>
        internal static string busqueda_tiempo {
            get {
                return ResourceManager.GetString("busqueda_tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totales.
        /// </summary>
        internal static string busqueda_totales {
            get {
                return ResourceManager.GetString("busqueda_totales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda.
        /// </summary>
        internal static string busquedaTitle {
            get {
                return ResourceManager.GetString("busquedaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        internal static string cbx_nigunaSeleccion {
            get {
                return ResourceManager.GetString("cbx_nigunaSeleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de ciudad.
        /// </summary>
        internal static string ciudad_altaCiudad {
            get {
                return ResourceManager.GetString("ciudad_altaCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja de ciudad.
        /// </summary>
        internal static string ciudad_bajaCiudad {
            get {
                return ResourceManager.GetString("ciudad_bajaCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar dato en ciudad.
        /// </summary>
        internal static string ciudad_cambiarDato {
            get {
                return ResourceManager.GetString("ciudad_cambiarDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenada x.
        /// </summary>
        internal static string ciudad_coordX {
            get {
                return ResourceManager.GetString("ciudad_coordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenada y.
        /// </summary>
        internal static string ciudad_coordY {
            get {
                return ResourceManager.GetString("ciudad_coordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudades existentes.
        /// </summary>
        internal static string ciudad_existentes {
            get {
                return ResourceManager.GetString("ciudad_existentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localización.
        /// </summary>
        internal static string ciudad_localizacion {
            get {
                return ResourceManager.GetString("ciudad_localizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la ciudad.
        /// </summary>
        internal static string ciudad_nombre {
            get {
                return ResourceManager.GetString("ciudad_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string ciudadTitle {
            get {
                return ResourceManager.GetString("ciudadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string info_idioma {
            get {
                return ResourceManager.GetString("info_idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planeador Turístico.
        /// </summary>
        internal static string info_nombre {
            get {
                return ResourceManager.GetString("info_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string informacionTitle {
            get {
                return ResourceManager.GetString("informacionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string menu_buscar {
            get {
                return ResourceManager.GetString("menu_buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsquedas.
        /// </summary>
        internal static string menu_busquedas {
            get {
                return ResourceManager.GetString("menu_busquedas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string menu_ciudad {
            get {
                return ResourceManager.GetString("menu_ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string menu_info {
            get {
                return ResourceManager.GetString("menu_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string menu_informacion {
            get {
                return ResourceManager.GetString("menu_informacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        internal static string menu_mapa {
            get {
                return ResourceManager.GetString("menu_mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string menu_ruta {
            get {
                return ResourceManager.GetString("menu_ruta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string menu_salir {
            get {
                return ResourceManager.GetString("menu_salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planeador Turístico.
        /// </summary>
        internal static string menuTitle_Planeacion {
            get {
                return ResourceManager.GetString("menuTitle_Planeacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alta de ruta.
        /// </summary>
        internal static string ruta_altaRuta {
            get {
                return ResourceManager.GetString("ruta_altaRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos si se utiliza carro rentado.
        /// </summary>
        internal static string ruta_autoPrivado {
            get {
                return ResourceManager.GetString("ruta_autoPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baja de ruta.
        /// </summary>
        internal static string ruta_bajaRuta {
            get {
                return ResourceManager.GetString("ruta_bajaRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar dato en una ruta.
        /// </summary>
        internal static string ruta_cambiarRuta {
            get {
                return ResourceManager.GetString("ruta_cambiarRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad de Inicio.
        /// </summary>
        internal static string ruta_ciudadInicio {
            get {
                return ResourceManager.GetString("ruta_ciudadInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad donde termina.
        /// </summary>
        internal static string ruta_ciudadTermina {
            get {
                return ResourceManager.GetString("ruta_ciudadTermina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo si se recorre en auto rentado.
        /// </summary>
        internal static string ruta_costoPrivado {
            get {
                return ResourceManager.GetString("ruta_costoPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo si se recorre en transporte público.
        /// </summary>
        internal static string ruta_costoPublico {
            get {
                return ResourceManager.GetString("ruta_costoPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distancia.
        /// </summary>
        internal static string ruta_distancia {
            get {
                return ResourceManager.GetString("ruta_distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la ruta.
        /// </summary>
        internal static string ruta_nombreRuta {
            get {
                return ResourceManager.GetString("ruta_nombreRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo si se recorre en auto rentado.
        /// </summary>
        internal static string ruta_tiempoPrivado {
            get {
                return ResourceManager.GetString("ruta_tiempoPrivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo si se recorre en transporte público.
        /// </summary>
        internal static string ruta_tiempoPublico {
            get {
                return ResourceManager.GetString("ruta_tiempoPublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos si se utiliza transporte público.
        /// </summary>
        internal static string ruta_transportePublico {
            get {
                return ResourceManager.GetString("ruta_transportePublico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutas existentes.
        /// </summary>
        internal static string rutas_existentes {
            get {
                return ResourceManager.GetString("rutas_existentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string rutaTitle {
            get {
                return ResourceManager.GetString("rutaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe una ruta alterna a la más corta.
        /// </summary>
        internal static string undirected_noRutaAlterna {
            get {
                return ResourceManager.GetString("undirected_noRutaAlterna", resourceCulture);
            }
        }
    }
}
